<?xml version = '1.0' encoding = 'utf-8'?>
<!--Generated by Oracle BI Publisher 12.2.1.4.0-->
<!--xslt1.0-compatibility-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDODEFDATE"/>
   <xsl:param name="_XDODEFTIME"/>
   <xsl:param name="_XDODEFNUM"/>
   <xsl:param name="_XDODEFCC"/>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, $_XDODFOVERRIDE, $_XDOCURMASKS, $_XDONFSEPARATORS)"/>
   <xsl:variable name="titlevar" select="'RTF Template'" xdofo:tobetranslated="true"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="84.6pt" margin-right="84.6pt" page-height="792.0pt" page-width="612.0pt" margin-top="36.0pt" margin-bottom="36.0pt">
               <fo:region-before region-name="region-header" extent="36.0pt"/>
               <fo:region-body region-name="region-body" margin-top="36.0pt" margin-bottom="36.0pt"/>
               <fo:region-after region-name="region-footer" extent="36.0pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>
               <xsl:value-of select="xdoxslt:one($titlevar)" xdofo:field-name="$titlevar"/>
            </fo:title>
            <xsl:variable name="_PW" select="number(612.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(792.0)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(90.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(90.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(72.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header"/>
            <fo:static-content flow-name="region-footer"/>
            <fo:flow flow-name="region-body">
               <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="5.4pt" start-indent="5.4pt" text-align="center" height="0.0pt">
                  <fo:inline font-family="Arial" height="10.404pt" font-family-generic="swiss" white-space-collapse="false" style-id="s0" color="#64748b" style-name="Normal" font-size="9.0pt">ORACLE E-BUSINESS SUITE R12</fo:inline>
               </fo:block>
               <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="5.4pt" start-indent="5.4pt" text-align="center" height="0.0pt">
                  <fo:inline font-family="Arial" height="10.404pt" font-family-generic="swiss" white-space-collapse="false" style-id="s0" color="#64748b" style-name="Normal" font-size="9.0pt">XX Custom Invoice Report</fo:inline>
               </fo:block>
               <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="5.4pt" start-indent="5.4pt" text-align="center" height="0.0pt">
                  <fo:inline font-family="Arial" height="10.404pt" font-family-generic="swiss" white-space-collapse="false" style-id="s0" color="#64748b" style-name="Normal" font-size="9.0pt">Application: AP  |  Report Code: XX_INV_REP  |  Oracle BI Publisher Template</fo:inline>
               </fo:block>
               <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="5.4pt" start-indent="5.4pt" text-align="start" height="13.392pt" font-family="Times New Roman" font-size="12.0pt" border-bottom="0.75pt solid #1e3a8a"/>
               <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="5.4pt" start-indent="5.4pt" text-align="start" height="13.392pt" font-family="Times New Roman" font-size="12.0pt"/>
               <fo:block text-align="start" padding-bottom="0.375pt" end-indent="5.4pt" padding-top="0.375pt" linefeed-treatment="preserve">
                  <fo:table start-indent="0.0pt" style-id="ts-1" xdofo:align="start" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
                     <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                     <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                     <fo:table-column column-width="89.4pt"/>
                     <fo:table-column column-width="84.0pt"/>
                     <fo:table-column column-width="84.0pt"/>
                     <fo:table-column column-width="84.0pt"/>
                     <fo:table-column column-width="18.0pt"/>
                     <fo:table-column column-width="66.0pt"/>
                     <fo:table-column column-width="84.0pt"/>
                     <fo:table-body>
                        <fo:table-row xdo-first-row="false" xdo-last-row="false" xdo-first-col="false" xdo-last-col="false" xdo-banded-row="true" xdo-banded-col="true">
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="1.0pt solid #1e3a8a" border-end-color="#1e3a8a" padding-top="0.0pt" border-end-style="solid" border-start-color="#1e3a8a" padding-end="0.0pt" number-columns-spanned="1" border-top="0.75pt solid #1e3a8a" border-start-style="solid" height="0.0pt" border-end-width="0.75pt" padding-bottom="0.0pt" border-start-width="0.75pt" background-color="#1e3a8a">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="center">
                                 <fo:inline color="#ffffff" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" font-weight="bold">Invoice ID</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="1.0pt solid #1e3a8a" border-end-color="#1e3a8a" padding-top="0.0pt" border-end-style="solid" border-start-color="#1e3a8a" padding-end="0.0pt" number-columns-spanned="1" border-top="0.75pt solid #1e3a8a" border-start-style="solid" height="0.0pt" border-end-width="0.75pt" padding-bottom="0.0pt" border-start-width="0.75pt" background-color="#1e3a8a">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="center">
                                 <fo:inline color="#ffffff" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" font-weight="bold">Invoice Number</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="1.0pt solid #1e3a8a" border-end-color="#1e3a8a" padding-top="0.0pt" border-end-style="solid" border-start-color="#1e3a8a" padding-end="0.0pt" number-columns-spanned="1" border-top="0.75pt solid #1e3a8a" border-start-style="solid" height="0.0pt" border-end-width="0.75pt" padding-bottom="0.0pt" border-start-width="0.75pt" background-color="#1e3a8a">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="center">
                                 <fo:inline color="#ffffff" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" font-weight="bold">Vendor Name</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="1.0pt solid #1e3a8a" border-end-color="#1e3a8a" padding-top="0.0pt" border-end-style="solid" border-start-color="#1e3a8a" padding-end="0.0pt" number-columns-spanned="1" border-top="0.75pt solid #1e3a8a" border-start-style="solid" height="0.0pt" border-end-width="0.75pt" padding-bottom="0.0pt" border-start-width="0.75pt" background-color="#1e3a8a">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="center">
                                 <fo:inline color="#ffffff" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" font-weight="bold">Invoice Date</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="1.0pt solid #1e3a8a" border-end-color="#1e3a8a" padding-top="0.0pt" border-end-style="solid" border-start-color="#1e3a8a" padding-end="0.0pt" number-columns-spanned="2" border-top="0.75pt solid #1e3a8a" border-start-style="solid" height="0.0pt" border-end-width="0.75pt" padding-bottom="0.0pt" border-start-width="0.75pt" background-color="#1e3a8a">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="center">
                                 <fo:inline color="#ffffff" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" font-weight="bold">Invoice Amount</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="1.0pt solid #1e3a8a" border-end-color="#1e3a8a" padding-top="0.0pt" border-end-style="solid" border-start-color="#1e3a8a" padding-end="0.0pt" number-columns-spanned="1" border-top="0.75pt solid #1e3a8a" border-start-style="solid" height="0.0pt" border-end-width="0.75pt" padding-bottom="0.0pt" border-start-width="0.75pt" background-color="#1e3a8a">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="center">
                                 <fo:inline color="#ffffff" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" font-weight="bold">Payment Status</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row xdo-first-row="false" xdo-last-row="false" xdo-first-col="false" xdo-last-col="false" xdo-banded-row="true" xdo-banded-col="true">
                           <xsl:for-each select=".//G_MAIN" xdofo:ctx="24">
                              <xsl:value-of select="xdoxslt:chkPrcCancel($_XDOXSLTCTX)"/>
                           </xsl:for-each>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="0.5pt solid #e2e8f0" border-end-color="#e2e8f0" padding-top="0.0pt" border-end-style="solid" border-start-color="#e2e8f0" padding-end="0.0pt" number-columns-spanned="1" border-top="0.5pt solid #e2e8f0" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="center">
                                 <fo:inline color="#0f172a" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman">
                                    <xsl:value-of select="(.//INVOICE_ID)[1]" xdofo:field-name="INVOICE_ID"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="0.5pt solid #e2e8f0" border-end-color="#e2e8f0" padding-top="0.0pt" border-end-style="solid" border-start-color="#e2e8f0" padding-end="0.0pt" number-columns-spanned="1" border-top="0.5pt solid #e2e8f0" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="start">
                                 <fo:inline color="#0f172a" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman">
                                    <xsl:value-of select="(.//INVOICE_NUM)[1]" xdofo:field-name="INVOICE_NUM"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="0.5pt solid #e2e8f0" border-end-color="#e2e8f0" padding-top="0.0pt" border-end-style="solid" border-start-color="#e2e8f0" padding-end="0.0pt" number-columns-spanned="1" border-top="0.5pt solid #e2e8f0" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="start">
                                 <fo:inline color="#0f172a" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman">
                                    <xsl:value-of select="(.//VENDOR_NAME)[1]" xdofo:field-name="VENDOR_NAME"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="0.5pt solid #e2e8f0" border-end-color="#e2e8f0" padding-top="0.0pt" border-end-style="solid" border-start-color="#e2e8f0" padding-end="0.0pt" number-columns-spanned="1" border-top="0.5pt solid #e2e8f0" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="start">
                                 <fo:inline color="#0f172a" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman">
                                    <xsl:value-of select="(.//INVOICE_DATE)[1]" xdofo:field-name="INVOICE_DATE"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="0.5pt solid #e2e8f0" border-end-color="#e2e8f0" padding-top="0.0pt" border-end-style="solid" border-start-color="#e2e8f0" padding-end="0.0pt" number-columns-spanned="2" border-top="0.5pt solid #e2e8f0" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="start">
                                 <fo:inline color="#0f172a" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman">
                                    <xsl:value-of select="(.//INVOICE_AMOUNT)[1]" xdofo:field-name="INVOICE_AMOUNT"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="0.5pt solid #e2e8f0" border-end-color="#e2e8f0" padding-top="0.0pt" border-end-style="solid" border-start-color="#e2e8f0" padding-end="0.0pt" number-columns-spanned="1" border-top="0.5pt solid #e2e8f0" border-start-style="solid" height="0.0pt" border-end-width="0.5pt" padding-bottom="0.0pt" border-start-width="0.5pt">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="start">
                                 <fo:inline color="#0f172a" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman">
                                    <xsl:value-of select="(.//PAYMENT_STATUS)[1]" xdofo:field-name="PAYMENT_STATUS"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                        <fo:table-row xdo-first-row="false" xdo-last-row="false" xdo-first-col="false" xdo-last-col="false" xdo-banded-row="true" xdo-banded-col="true">
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="0.75pt solid #1e3a8a" border-end-color="#1e3a8a" padding-top="0.0pt" border-end-style="solid" border-start-color="#1e3a8a" padding-end="0.0pt" number-columns-spanned="5" border-top="0.75pt solid #1e3a8a" border-start-style="solid" height="0.0pt" border-end-width="0.75pt" padding-bottom="0.0pt" border-start-width="0.75pt" background-color="#eef2ff">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="right">
                                 <fo:inline color="#1e3a8a" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" font-weight="bold">Total Records Count:</fo:inline>
                              </fo:block>
                           </fo:table-cell>
                           <fo:table-cell padding-start="0.0pt" vertical-align="top" border-bottom="0.75pt solid #1e3a8a" border-end-color="#1e3a8a" padding-top="0.0pt" border-end-style="solid" border-start-color="#1e3a8a" padding-end="0.0pt" number-columns-spanned="2" border-top="0.75pt solid #1e3a8a" border-start-style="solid" height="0.0pt" border-end-width="0.75pt" padding-bottom="0.0pt" border-start-width="0.75pt" background-color="#eef2ff">
                              <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="0.0pt" start-indent="0.0pt" text-align="center">
                                 <fo:inline color="#1e3a8a" font-size="8.5pt" style-name="Normal" height="8.5pt" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" font-weight="bold">
                                    <xsl:value-of select="count(.//INVOICE_ID)" xdofo:field-name="count(INVOICE_ID)"/>
                                 </fo:inline>
                              </fo:block>
                           </fo:table-cell>
                        </fo:table-row>
                     </fo:table-body>
                  </fo:table>
               </fo:block>
               <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="5.4pt" start-indent="5.4pt" text-align="start" height="13.392pt" font-family="Times New Roman" font-size="12.0pt"/>
               <fo:block padding-top="0.0pt" linefeed-treatment="preserve" padding-bottom="0.0pt" end-indent="5.4pt" start-indent="5.4pt" text-align="right" height="0.0pt">
                  <fo:inline xml:space="preserve" style-id="s0" white-space-collapse="false" font-family="Times New Roman" font-family-generic="Roman" height="8.928pt" style-name="Normal" font-size="8.0pt" color="#64748b">Confidential - Oracle EBS GeneratedPage <xsl:value-of select="(.//page_number)[1]" xdofo:field-name="page_number"/> of <xsl:value-of select="(.//total_pages)[1]" xdofo:field-name="total_pages"/></fo:inline>
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
